### ISSUE TITLE
How to provide link to a specific commit?

### ISSUE THREAD

**Issue by Zhang-Haipeng** [UBC-MDS/DSCI-532_group-203_Lab1-2#19]
Hey @cgostic @lori94 , regarding the message in the instruction: `• Important: the links you provide to your code on GitHub.com should point to a specific commit so we can mark the version you submitted as you continue to work on the project.`  Do you have any thoughts on this? How to do it and does it matter for milestone1?

**Comment by cgostic** [comment]
I believe we're meant to link to a commit like:
 https://github.com/UBC-MDS/DSCI-532_group-203_Lab1-2/commit/bafa4525c0679b006342d6be71ce188063b1d421

Instead of just the file link on the repo in case we make any changes to work on next week's assignment before they grade milestone 1.

**Comment by Zhang-Haipeng** [comment]
> I believe we're meant to link to a commit like:
> [bafa452](https://github.com/UBC-MDS/DSCI-532_group-203_Lab1-2/commit/bafa4525c0679b006342d6be71ce188063b1d421)
> 
> Instead of just the file link on the repo in case we make any changes to work on next week's assignment before they grade milestone 1.

Oh right, make sense.  Then they can click on the `Browse files` button to see the files at that version.   
And I noticed we can also provide links directly to the files like this: https://github.com/UBC-MDS/DSCI-532_group-203_Lab1-2/tree/d113ec41db9f7a47e80fe2348350ca0c74326ebd
