### ISSUE TITLE
Code of Conduct needs reviewing

### ISSUE THREAD

**Issue by cgostic** [UBC-MDS/DSCI-532_group-203_Lab1-2#7]
Submitted a pull request for a CODE_OF_CONDUCT.md file with @Zhang-Haipeng as reviewer.

**Comment by cgostic** [comment]
To do: update CONTRIBUTING.md with provided snippet and link to CODE_OF_CONDUCT.md

**Comment by Zhang-Haipeng** [comment]
PR merged.
